//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/**
 * Copyright 2021 Appvia Ltd <info@appvia.io>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionSelector) DeepCopyInto(out *ActionSelector) {
	*out = *in
	if in.Verbs != nil {
		in, out := &in.Verbs, &out.Verbs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionSelector.
func (in *ActionSelector) DeepCopy() *ActionSelector {
	if in == nil {
		return nil
	}
	out := new(ActionSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppEnvRef) DeepCopyInto(out *AppEnvRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppEnvRef.
func (in *AppEnvRef) DeepCopy() *AppEnvRef {
	if in == nil {
		return nil
	}
	out := new(AppEnvRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudAccessConfigRef) DeepCopyInto(out *CloudAccessConfigRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudAccessConfigRef.
func (in *CloudAccessConfigRef) DeepCopy() *CloudAccessConfigRef {
	if in == nil {
		return nil
	}
	out := new(CloudAccessConfigRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudResource) DeepCopyInto(out *CloudResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudResource.
func (in *CloudResource) DeepCopy() *CloudResource {
	if in == nil {
		return nil
	}
	out := new(CloudResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudResourceRef) DeepCopyInto(out *CloudResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudResourceRef.
func (in *CloudResourceRef) DeepCopy() *CloudResourceRef {
	if in == nil {
		return nil
	}
	out := new(CloudResourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCapabilitiesList) DeepCopyInto(out *ClusterCapabilitiesList) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterCapability, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCapabilitiesList.
func (in *ClusterCapabilitiesList) DeepCopy() *ClusterCapabilitiesList {
	if in == nil {
		return nil
	}
	out := new(ClusterCapabilitiesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCapability) DeepCopyInto(out *ClusterCapability) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCapability.
func (in *ClusterCapability) DeepCopy() *ClusterCapability {
	if in == nil {
		return nil
	}
	out := new(ClusterCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCapabilitySpec) DeepCopyInto(out *ClusterCapabilitySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCapabilitySpec.
func (in *ClusterCapabilitySpec) DeepCopy() *ClusterCapabilitySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterCapabilitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNetworkRef) DeepCopyInto(out *ClusterNetworkRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNetworkRef.
func (in *ClusterNetworkRef) DeepCopy() *ClusterNetworkRef {
	if in == nil {
		return nil
	}
	out := new(ClusterNetworkRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPackage) DeepCopyInto(out *ClusterPackage) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPackage.
func (in *ClusterPackage) DeepCopy() *ClusterPackage {
	if in == nil {
		return nil
	}
	out := new(ClusterPackage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPackageCapability) DeepCopyInto(out *ClusterPackageCapability) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPackageCapability.
func (in *ClusterPackageCapability) DeepCopy() *ClusterPackageCapability {
	if in == nil {
		return nil
	}
	out := new(ClusterPackageCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPackageSpec) DeepCopyInto(out *ClusterPackageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPackageSpec.
func (in *ClusterPackageSpec) DeepCopy() *ClusterPackageSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterPackageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPackagesList) DeepCopyInto(out *ClusterPackagesList) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterPackage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPackagesList.
func (in *ClusterPackagesList) DeepCopy() *ClusterPackagesList {
	if in == nil {
		return nil
	}
	out := new(ClusterPackagesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRef) DeepCopyInto(out *ClusterRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRef.
func (in *ClusterRef) DeepCopy() *ClusterRef {
	if in == nil {
		return nil
	}
	out := new(ClusterRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonStatus) DeepCopyInto(out *CommonStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PendingSince != nil {
		in, out := &in.PendingSince, &out.PendingSince
		*out = new(LastReconcileStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastReconcile != nil {
		in, out := &in.LastReconcile, &out.LastReconcile
		*out = new(LastReconcileStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastSuccess != nil {
		in, out := &in.LastSuccess, &out.LastSuccess
		*out = new(LastReconcileStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ObsoleteResources != nil {
		in, out := &in.ObsoleteResources, &out.ObsoleteResources
		*out = make(ObsoleteResourceList, len(*in))
		copy(*out, *in)
	}
	in.OwnedResources.DeepCopyInto(&out.OwnedResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonStatus.
func (in *CommonStatus) DeepCopy() *CommonStatus {
	if in == nil {
		return nil
	}
	out := new(CommonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	if in.LogDetails != nil {
		in, out := &in.LogDetails, &out.LogDetails
		*out = new(LogDetails)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionSpec) DeepCopyInto(out *ConditionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionSpec.
func (in *ConditionSpec) DeepCopy() *ConditionSpec {
	if in == nil {
		return nil
	}
	out := new(ConditionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ConditionSpecs) DeepCopyInto(out *ConditionSpecs) {
	{
		in := &in
		*out = make(ConditionSpecs, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionSpecs.
func (in ConditionSpecs) DeepCopy() ConditionSpecs {
	if in == nil {
		return nil
	}
	out := new(ConditionSpecs)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Conditions) DeepCopyInto(out *Conditions) {
	{
		in := &in
		*out = make(Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Conditions.
func (in Conditions) DeepCopy() Conditions {
	if in == nil {
		return nil
	}
	out := new(Conditions)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationFromSource) DeepCopyInto(out *ConfigurationFromSource) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(OptionalSecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationFromSource.
func (in *ConfigurationFromSource) DeepCopy() *ConfigurationFromSource {
	if in == nil {
		return nil
	}
	out := new(ConfigurationFromSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ConfigurationFromSourceList) DeepCopyInto(out *ConfigurationFromSourceList) {
	{
		in := &in
		*out = make(ConfigurationFromSourceList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationFromSourceList.
func (in ConfigurationFromSourceList) DeepCopy() ConfigurationFromSourceList {
	if in == nil {
		return nil
	}
	out := new(ConfigurationFromSourceList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSEntry) DeepCopyInto(out *DNSEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSEntry.
func (in *DNSEntry) DeepCopy() *DNSEntry {
	if in == nil {
		return nil
	}
	out := new(DNSEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSZoneRef) DeepCopyInto(out *DNSZoneRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSZoneRef.
func (in *DNSZoneRef) DeepCopy() *DNSZoneRef {
	if in == nil {
		return nil
	}
	out := new(DNSZoneRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludedFile) DeepCopyInto(out *IncludedFile) {
	*out = *in
	if in.Content != nil {
		in, out := &in.Content, &out.Content
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludedFile.
func (in *IncludedFile) DeepCopy() *IncludedFile {
	if in == nil {
		return nil
	}
	out := new(IncludedFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in IncludedFiles) DeepCopyInto(out *IncludedFiles) {
	{
		in := &in
		*out = make(IncludedFiles, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludedFiles.
func (in IncludedFiles) DeepCopy() IncludedFiles {
	if in == nil {
		return nil
	}
	out := new(IncludedFiles)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputContext) DeepCopyInto(out *InputContext) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make(InputValues, len(*in))
		copy(*out, *in)
	}
	if in.Vars != nil {
		in, out := &in.Vars, &out.Vars
		*out = make([]Var, len(*in))
		copy(*out, *in)
	}
	if in.InputDeps != nil {
		in, out := &in.InputDeps, &out.InputDeps
		*out = make([]InputDependency, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputContext.
func (in *InputContext) DeepCopy() *InputContext {
	if in == nil {
		return nil
	}
	out := new(InputContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputDefinition) DeepCopyInto(out *InputDefinition) {
	*out = *in
	in.Validation.DeepCopyInto(&out.Validation)
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputDefinition.
func (in *InputDefinition) DeepCopy() *InputDefinition {
	if in == nil {
		return nil
	}
	out := new(InputDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in InputDefinitions) DeepCopyInto(out *InputDefinitions) {
	{
		in := &in
		*out = make(InputDefinitions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputDefinitions.
func (in InputDefinitions) DeepCopy() InputDefinitions {
	if in == nil {
		return nil
	}
	out := new(InputDefinitions)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputDependency) DeepCopyInto(out *InputDependency) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputDependency.
func (in *InputDependency) DeepCopy() *InputDependency {
	if in == nil {
		return nil
	}
	out := new(InputDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputValidationDefinition) DeepCopyInto(out *InputValidationDefinition) {
	*out = *in
	if in.MinLength != nil {
		in, out := &in.MinLength, &out.MinLength
		*out = new(int)
		**out = **in
	}
	if in.MaxLength != nil {
		in, out := &in.MaxLength, &out.MaxLength
		*out = new(int)
		**out = **in
	}
	if in.Pattern != nil {
		in, out := &in.Pattern, &out.Pattern
		*out = new(string)
		**out = **in
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputValidationDefinition.
func (in *InputValidationDefinition) DeepCopy() *InputValidationDefinition {
	if in == nil {
		return nil
	}
	out := new(InputValidationDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputValue) DeepCopyInto(out *InputValue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputValue.
func (in *InputValue) DeepCopy() *InputValue {
	if in == nil {
		return nil
	}
	out := new(InputValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in InputValues) DeepCopyInto(out *InputValues) {
	{
		in := &in
		*out = make(InputValues, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputValues.
func (in InputValues) DeepCopy() InputValues {
	if in == nil {
		return nil
	}
	out := new(InputValues)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobStatus) DeepCopyInto(out *JobStatus) {
	*out = *in
	if in.RunStatus != nil {
		in, out := &in.RunStatus, &out.RunStatus
		*out = make([]RunStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.LastProcessed = in.LastProcessed
	out.LastProcessedDelete = in.LastProcessedDelete
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobStatus.
func (in *JobStatus) DeepCopy() *JobStatus {
	if in == nil {
		return nil
	}
	out := new(JobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastProcessedInfo) DeepCopyInto(out *LastProcessedInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastProcessedInfo.
func (in *LastProcessedInfo) DeepCopy() *LastProcessedInfo {
	if in == nil {
		return nil
	}
	out := new(LastProcessedInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastReconcileStatus) DeepCopyInto(out *LastReconcileStatus) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastReconcileStatus.
func (in *LastReconcileStatus) DeepCopy() *LastReconcileStatus {
	if in == nil {
		return nil
	}
	out := new(LastReconcileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogDetails) DeepCopyInto(out *LogDetails) {
	*out = *in
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogDetails.
func (in *LogDetails) DeepCopy() *LogDetails {
	if in == nil {
		return nil
	}
	out := new(LogDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceClaimRef) DeepCopyInto(out *NamespaceClaimRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceClaimRef.
func (in *NamespaceClaimRef) DeepCopy() *NamespaceClaimRef {
	if in == nil {
		return nil
	}
	out := new(NamespaceClaimRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObsoleteResource) DeepCopyInto(out *ObsoleteResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObsoleteResource.
func (in *ObsoleteResource) DeepCopy() *ObsoleteResource {
	if in == nil {
		return nil
	}
	out := new(ObsoleteResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ObsoleteResourceList) DeepCopyInto(out *ObsoleteResourceList) {
	{
		in := &in
		*out = make(ObsoleteResourceList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObsoleteResourceList.
func (in ObsoleteResourceList) DeepCopy() ObsoleteResourceList {
	if in == nil {
		return nil
	}
	out := new(ObsoleteResourceList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptionalSecretKeySelector) DeepCopyInto(out *OptionalSecretKeySelector) {
	*out = *in
	out.SecretKeySelector = in.SecretKeySelector
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptionalSecretKeySelector.
func (in *OptionalSecretKeySelector) DeepCopy() *OptionalSecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(OptionalSecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Output) DeepCopyInto(out *Output) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Output.
func (in *Output) DeepCopy() *Output {
	if in == nil {
		return nil
	}
	out := new(Output)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutputDefinition) DeepCopyInto(out *OutputDefinition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutputDefinition.
func (in *OutputDefinition) DeepCopy() *OutputDefinition {
	if in == nil {
		return nil
	}
	out := new(OutputDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnedResources) DeepCopyInto(out *OwnedResources) {
	*out = *in
	if in.WayfinderResources != nil {
		in, out := &in.WayfinderResources, &out.WayfinderResources
		*out = make([]WayfinderResource, len(*in))
		copy(*out, *in)
	}
	if in.CloudResources != nil {
		in, out := &in.CloudResources, &out.CloudResources
		*out = make([]CloudResource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnedResources.
func (in *OwnedResources) DeepCopy() *OwnedResources {
	if in == nil {
		return nil
	}
	out := new(OwnedResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ownership) DeepCopyInto(out *Ownership) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ownership.
func (in *Ownership) DeepCopy() *Ownership {
	if in == nil {
		return nil
	}
	out := new(Ownership)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageRef) DeepCopyInto(out *PackageRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageRef.
func (in *PackageRef) DeepCopy() *PackageRef {
	if in == nil {
		return nil
	}
	out := new(PackageRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanPolicy) DeepCopyInto(out *PlanPolicy) {
	*out = *in
	if in.Editable != nil {
		in, out := &in.Editable, &out.Editable
		*out = new(bool)
		**out = **in
	}
	if in.Enum != nil {
		in, out := &in.Enum, &out.Enum
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(int64)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanPolicy.
func (in *PlanPolicy) DeepCopy() *PlanPolicy {
	if in == nil {
		return nil
	}
	out := new(PlanPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanRef) DeepCopyInto(out *PlanRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanRef.
func (in *PlanRef) DeepCopy() *PlanRef {
	if in == nil {
		return nil
	}
	out := new(PlanRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanSpec) DeepCopyInto(out *PlanSpec) {
	*out = *in
	in.Allocation.DeepCopyInto(&out.Allocation)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]*PlanPolicy, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(PlanPolicy)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanSpec.
func (in *PlanSpec) DeepCopy() *PlanSpec {
	if in == nil {
		return nil
	}
	out := new(PlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublishingState) DeepCopyInto(out *PublishingState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublishingState.
func (in *PublishingState) DeepCopy() *PublishingState {
	if in == nil {
		return nil
	}
	out := new(PublishingState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceAllocation) DeepCopyInto(out *ResourceAllocation) {
	*out = *in
	if in.Workspaces != nil {
		in, out := &in.Workspaces, &out.Workspaces
		*out = make(WorkspaceKeys, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceAllocation.
func (in *ResourceAllocation) DeepCopy() *ResourceAllocation {
	if in == nil {
		return nil
	}
	out := new(ResourceAllocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSelector) DeepCopyInto(out *ResourceSelector) {
	*out = *in
	if in.NonResourceURLs != nil {
		in, out := &in.NonResourceURLs, &out.NonResourceURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SubResources != nil {
		in, out := &in.SubResources, &out.SubResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResourceNames != nil {
		in, out := &in.ResourceNames, &out.ResourceNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Verbs != nil {
		in, out := &in.Verbs, &out.Verbs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSelector.
func (in *ResourceSelector) DeepCopy() *ResourceSelector {
	if in == nil {
		return nil
	}
	out := new(ResourceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingStatus) DeepCopyInto(out *RoutingStatus) {
	*out = *in
	if in.Routing != nil {
		in, out := &in.Routing, &out.Routing
		*out = make(RoutingTargetStatuses, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingStatus.
func (in *RoutingStatus) DeepCopy() *RoutingStatus {
	if in == nil {
		return nil
	}
	out := new(RoutingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingTargetStatus) DeepCopyInto(out *RoutingTargetStatus) {
	*out = *in
	out.Target = in.Target
	if in.LastReconcile != nil {
		in, out := &in.LastReconcile, &out.LastReconcile
		*out = new(LastReconcileStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingTargetStatus.
func (in *RoutingTargetStatus) DeepCopy() *RoutingTargetStatus {
	if in == nil {
		return nil
	}
	out := new(RoutingTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in RoutingTargetStatuses) DeepCopyInto(out *RoutingTargetStatuses) {
	{
		in := &in
		*out = make(RoutingTargetStatuses, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingTargetStatuses.
func (in RoutingTargetStatuses) DeepCopy() RoutingTargetStatuses {
	if in == nil {
		return nil
	}
	out := new(RoutingTargetStatuses)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunStatus) DeepCopyInto(out *RunStatus) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	in.LastCheckedTime.DeepCopyInto(&out.LastCheckedTime)
	if in.FinishTime != nil {
		in, out := &in.FinishTime, &out.FinishTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunStatus.
func (in *RunStatus) DeepCopy() *RunStatus {
	if in == nil {
		return nil
	}
	out := new(RunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Scope) DeepCopyInto(out *Scope) {
	*out = *in
	in.ScopeWorkspace.DeepCopyInto(&out.ScopeWorkspace)
	in.ScopeStages.DeepCopyInto(&out.ScopeStages)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Scope.
func (in *Scope) DeepCopy() *Scope {
	if in == nil {
		return nil
	}
	out := new(Scope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopeStages) DeepCopyInto(out *ScopeStages) {
	*out = *in
	if in.AllowedStages != nil {
		in, out := &in.AllowedStages, &out.AllowedStages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeStages.
func (in *ScopeStages) DeepCopy() *ScopeStages {
	if in == nil {
		return nil
	}
	out := new(ScopeStages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopeWorkspace) DeepCopyInto(out *ScopeWorkspace) {
	*out = *in
	if in.AllowedWorkspaces != nil {
		in, out := &in.AllowedWorkspaces, &out.AllowedWorkspaces
		*out = make(WorkspaceKeys, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeWorkspace.
func (in *ScopeWorkspace) DeepCopy() *ScopeWorkspace {
	if in == nil {
		return nil
	}
	out := new(ScopeWorkspace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubjectSelector) DeepCopyInto(out *SubjectSelector) {
	*out = *in
	if in.Subjects != nil {
		in, out := &in.Subjects, &out.Subjects
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubjectSelector.
func (in *SubjectSelector) DeepCopy() *SubjectSelector {
	if in == nil {
		return nil
	}
	out := new(SubjectSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateSpec) DeepCopyInto(out *UpdateSpec) {
	*out = *in
	if in.PreRequisite != nil {
		in, out := &in.PreRequisite, &out.PreRequisite
		*out = new(UpdateStep)
		**out = **in
	}
	if in.Next != nil {
		in, out := &in.Next, &out.Next
		*out = new(UpdateStep)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSpec.
func (in *UpdateSpec) DeepCopy() *UpdateSpec {
	if in == nil {
		return nil
	}
	out := new(UpdateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateStatus) DeepCopyInto(out *UpdateStatus) {
	*out = *in
	out.PreRequisite = in.PreRequisite
	in.StartTime.DeepCopyInto(&out.StartTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateStatus.
func (in *UpdateStatus) DeepCopy() *UpdateStatus {
	if in == nil {
		return nil
	}
	out := new(UpdateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateStep) DeepCopyInto(out *UpdateStep) {
	*out = *in
	out.Owner = in.Owner
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateStep.
func (in *UpdateStep) DeepCopy() *UpdateStep {
	if in == nil {
		return nil
	}
	out := new(UpdateStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateStepStatus) DeepCopyInto(out *UpdateStepStatus) {
	*out = *in
	out.Owner = in.Owner
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateStepStatus.
func (in *UpdateStepStatus) DeepCopy() *UpdateStepStatus {
	if in == nil {
		return nil
	}
	out := new(UpdateStepStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in UpdateSteps) DeepCopyInto(out *UpdateSteps) {
	{
		in := &in
		*out = make(UpdateSteps, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSteps.
func (in UpdateSteps) DeepCopy() UpdateSteps {
	if in == nil {
		return nil
	}
	out := new(UpdateSteps)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Var) DeepCopyInto(out *Var) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Var.
func (in *Var) DeepCopy() *Var {
	if in == nil {
		return nil
	}
	out := new(Var)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Vars) DeepCopyInto(out *Vars) {
	{
		in := &in
		*out = make(Vars, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Vars.
func (in Vars) DeepCopy() Vars {
	if in == nil {
		return nil
	}
	out := new(Vars)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WayfinderResource) DeepCopyInto(out *WayfinderResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WayfinderResource.
func (in *WayfinderResource) DeepCopy() *WayfinderResource {
	if in == nil {
		return nil
	}
	out := new(WayfinderResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in WorkspaceKeys) DeepCopyInto(out *WorkspaceKeys) {
	{
		in := &in
		*out = make(WorkspaceKeys, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceKeys.
func (in WorkspaceKeys) DeepCopy() WorkspaceKeys {
	if in == nil {
		return nil
	}
	out := new(WorkspaceKeys)
	in.DeepCopyInto(out)
	return *out
}
